# pubspec.yaml

name: project_beauty_admin
description: A new Flutter project for Beauty Salon Admin Panel.

# The following line ensures that the Material Icons font is
# included with your application, so that you can use the icons in
# the Material Icons class.
uses-material-design: true

# To add assets to your application, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg

# An image asset can be specified here to be used as the application's
# top-level icon. This icon and others in the build will be
# overridden in favor of a higher-resolution icon when a non-default
# icon file is provided.
# flutter:
#   assets:
#     - images/a_dot_burr.jpeg
#     - images/a_dot_ham.jpeg

# Fonts
# To add custom fonts to your application, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages

version: 1.0.0+1 # Uygulama versiyonu

environment:
  sdk: '>=3.8.1 <4.0.0' # Dart SDK 3.8.1 ile uyumlu hale getirildi

dependencies:
  flutter:
    sdk: flutter # Flutter SDK'sının doğru tanımı burada
  table_calendar: ^3.0.9
  cupertino_icons: ^1.0.6   # iOS tarzı ikonlar için
  google_fonts: ^6.2.1      # Poppins fontunu kolayca kullanmak için
  intl: ^0.19.0             # Tarih ve saat formatlama için

  # Veritabanı ve Kimlik Doğrulama İçin Firebase Bağımlılıkları
  firebase_core: ^2.27.0    # Firebase'in temel paketi
  firebase_auth: ^4.17.8    # Firebase kimlik doğrulama için
  cloud_firestore: ^4.15.8  # Firestore veritabanı için

  # Tema ve kullanıcı tercihleri gibi basit verileri kaydetmek için
  shared_preferences: ^2.2.3

  # State management için (isteğe bağlı, ileride kullanabiliriz)
  # provider: ^6.1.2 # Ya da flutter_bloc, riverpod gibi tercihine göre

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Dart SDK 3.5.0 ve üzeri ile uyumlu
