name: project_beauty_admin
description: "A new Flutter project for Beauty Salon Admin Panel."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Yerelleştirme (DatePicker vb. için gerekli)
  flutter_localizations:
    sdk: flutter
  fl_chart: ^0.68.0
  # Supabase
  supabase_flutter: ^2.5.2

  # State management
  provider: ^6.1.2

  # .env
  flutter_dotenv: ^5.1.0

  # Tarih/saat
  intl: ^0.20.2

  # UI
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logos/
